const testimonials = [
    {
        id: 1,
        name: "Rajesh Sharma",
        company: "Multiplus Construction",
        content: "The web development team at Multiplus was outstanding. They delivered a top-notch website that perfectly showcases our construction projects.",
        service: "Web Development",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 2,
        name: "Priya Kapoor",
        company: "KP Metals",
        content: "We needed an eCommerce website, and the team exceeded our expectations. The site is user-friendly and has significantly boosted our sales.",
        service: "eCommerce Website",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 3,
        name: "Vikram Desai",
        company: "UCS Booking",
        content: "The booking system they developed for us is seamless and has improved our customer satisfaction. Highly recommended!",
        service: "Web Development",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 4,
        name: "Anjali Mehta",
        company: "KP Metals",
        content: "Their graphic design work is top-tier. The brochures and marketing materials they created for us have been a hit with our clients.",
        service: "Graphic Designing",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 5,
        name: "Rohan Patel",
        company: "Multiplus Construction",
        content: "Our new website is fantastic! It’s not only visually appealing but also easy to navigate, thanks to the excellent work of their web development team.",
        service: "Web Development",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 6,
        name: "Neha Sinha",
        company: "UCS Booking",
        content: "The digital marketing strategies they implemented have greatly increased our online presence. We’re getting more leads than ever!",
        service: "Digital Marketing",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 7,
        name: "Amit Chawla",
        company: "KP Metals",
        content: "We are thrilled with our eCommerce website. It’s fast, secure, and offers a smooth shopping experience for our customers.",
        service: "eCommerce Website",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 8,
        name: "Sonal Joshi",
        company: "Multiplus Construction",
        content: "Their graphic design for our branding materials was spot-on. We’ve received numerous compliments on our new look.",
        service: "Graphic Designing",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 9,
        name: "Arjun Gupta",
        company: "UCS Booking",
        content: "Their web development services are exceptional. They built us a custom solution that meets all our booking needs.",
        service: "Web Development",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 10,
        name: "Divya Agarwal",
        company: "KP Metals",
        content: "The eCommerce site they developed for us has made shopping easier for our customers and streamlined our sales process.",
        service: "eCommerce Website",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 11,
        name: "Kiran Rao",
        company: "Multiplus Construction",
        content: "We’re incredibly satisfied with the web development service provided. The website is exactly what we envisioned and more.",
        service: "Web Development",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 12,
        name: "Nisha Verma",
        company: "UCS Booking",
        content: "Their digital marketing strategies have helped us reach a broader audience and increase our bookings significantly.",
        service: "Digital Marketing",
        image: "https://via.placeholder.com/150",
    },
];

export default testimonials